<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <StartupObject>X5Control.Program</StartupObject>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
    <Content Include="src\Ui\StageWindow.xaml" Link="MainWindow.xaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
